app:
  name: GoBankingAuth
  version: 1.0.0
server:
  port: 8282
  host: 127.0.0.1
  apikey: secret
database:
  user: root
  password: Password1234
  host: localhost
  port: 3306
  name: banking
  driver: mysql